# Generated by Django 4.0.2 on 2022-02-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер списка')),
                ('name', models.CharField(max_length=250, verbose_name='Название списка')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_done_tasks', models.BooleanField(verbose_name='Показывать выполненные задачи')),
                ('tasks_order', models.IntegerField(choices=[(0, 'Chronological'), (1, 'By creating date'), (2, 'By to be done date')], verbose_name='Порядок сортировки')),
                ('play_sound', models.BooleanField(verbose_name='Проигрывать звук при выполнении')),
                ('reversed_order', models.BooleanField(verbose_name='Показывать задачи в обратном порядке')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Название задачи')),
                ('done', models.BooleanField(verbose_name='Задача выполнена')),
                ('in_list', models.BooleanField(verbose_name='Задача отображается в общем списке')),
                ('parent', models.IntegerField(verbose_name='Родительская подзадача')),
                ('description', models.TextField(verbose_name='Заметка')),
                ('create_date', models.DateTimeField(verbose_name='Дата создания задачи')),
                ('modify_date', models.DateTimeField(verbose_name='Дата последнего изменения задачи')),
                ('deadline', models.DateTimeField(verbose_name='Дата выполнения задачи')),
                ('color', models.CharField(max_length=6, verbose_name='Цвет')),
                ('subtasks', models.JSONField(verbose_name='Подзадачи')),
                ('list_id', models.IntegerField(verbose_name='Номер родительского списка')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
